### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by remymateus** [ttdat89/cordova-plugin-lucky-clover-image-filter#1]
Hello, could you give us information on how to use this plugin?
Thanks.

**Comment by ttdatt** [comment]
Hi @remymateus, this plugin use https://github.com/BradLarson/GPUImage for iOS and https://github.com/CyberAgent/android-gpuimage for Android to create some image effects that we can apply to an image (it's like image filter on Instagram when you post an image). If this feature is what you need, then I will add a guide how to use it.

**Comment by remymateus** [comment]
Hi @ttdat89 , yes this this feature is what i need. Thanks !
